// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE9TiOIKlMpvpYF18JdrPs99XBleK_m1Q',
    appId: '1:151818032865:web:eaaa0823cb111456ca49a0',
    messagingSenderId: '151818032865',
    projectId: 'fixo-chat',
    authDomain: 'fixo-chat.firebaseapp.com',
    databaseURL: 'https://fixo-chat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fixo-chat.firebasestorage.app',
    measurementId: 'G-T4T0YGT43S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByg7c1t4VBp9n4rQGeIKelqaMpdDSJKRA',
    appId: '1:151818032865:android:dbdf567bf5151420ca49a0',
    messagingSenderId: '151818032865',
    projectId: 'fixo-chat',
    databaseURL: 'https://fixo-chat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fixo-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX_Pe_ytJYhpGHyXH7gg-dGZSTXUeKiHI',
    appId: '1:151818032865:ios:0a73766e0d5ba265ca49a0',
    messagingSenderId: '151818032865',
    projectId: 'fixo-chat',
    databaseURL: 'https://fixo-chat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fixo-chat.firebasestorage.app',
    iosBundleId: 'com.example.fixoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX_Pe_ytJYhpGHyXH7gg-dGZSTXUeKiHI',
    appId: '1:151818032865:ios:0a73766e0d5ba265ca49a0',
    messagingSenderId: '151818032865',
    projectId: 'fixo-chat',
    databaseURL: 'https://fixo-chat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fixo-chat.firebasestorage.app',
    iosBundleId: 'com.example.fixoChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE9TiOIKlMpvpYF18JdrPs99XBleK_m1Q',
    appId: '1:151818032865:web:fc8cdcaae668953eca49a0',
    messagingSenderId: '151818032865',
    projectId: 'fixo-chat',
    authDomain: 'fixo-chat.firebaseapp.com',
    databaseURL: 'https://fixo-chat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fixo-chat.firebasestorage.app',
    measurementId: 'G-5FBFYGRJPN',
  );
}
