import 'package:cloud_firestore/cloud_firestore.dart';

/// Service to generate auto-increment IDs for users
class IdGeneratorService {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Get next auto-increment ID - shared sequence for both user types
  static Future<int> getNextUserId(String userType) async {
    // Get the highest ID from both collections
    return await _firestore.runTransaction<int>((transaction) async {
      // Get all homeowners and tradies to find the highest ID
      final homeownersSnapshot = await _firestore
          .collection('homeowners')
          .get();
      final tradiesSnapshot = await _firestore.collection('tradies').get();

      int highestId = 0;

      // Check homeowners for highest ID
      for (final doc in homeownersSnapshot.docs) {
        final data = doc.data();
        final id = data['id'] as int? ?? 0;
        if (id > highestId) {
          highestId = id;
        }
      }

      // Check tradies for highest ID
      for (final doc in tradiesSnapshot.docs) {
        final data = doc.data();
        final id = data['id'] as int? ?? 0;
        if (id > highestId) {
          highestId = id;
        }
      }

      // Return next ID (highest + 1, or 1 if no users exist)
      return highestId + 1;
    });
  }

  /// No counter initialization needed - IDs are generated from existing data
  static Future<void> initializeCounters() async {
    print('✅ No counter collection needed');
    print(
      '   - Both homeowners and tradies share same ID sequence: 1, 2, 3, 4...',
    );
    print('   - IDs are generated by finding highest existing ID + 1');
  }

  /// Add auto-increment IDs to existing users
  static Future<void> addIdsToExistingUsers() async {
    print('🔄 Adding auto-increment IDs to existing users...');

    // Process homeowners
    await _addIdsToCollection('homeowners', 'homeowner');

    // Process tradies
    await _addIdsToCollection('tradies', 'tradie');

    print('✅ All existing users now have auto-increment IDs');
  }

  static Future<void> _addIdsToCollection(
    String collectionName,
    String userType,
  ) async {
    print('📝 Processing $collectionName...');

    final snapshot = await _firestore.collection(collectionName).get();

    if (snapshot.docs.isEmpty) {
      print('⚠️ No documents found in $collectionName');
      return;
    }

    int updatedCount = 0;
    for (final doc in snapshot.docs) {
      final data = doc.data();

      // Check if ID already exists
      if (data['id'] == null) {
        // Get next auto-increment ID
        final nextId = await getNextUserId(userType);

        // Add ID to document
        await doc.reference.update({'id': nextId});

        print('✅ Added ID $nextId to ${data['name'] ?? 'Unknown'} (${doc.id})');
        updatedCount++;
      } else {
        print('ℹ️ ${data['name']} already has ID: ${data['id']}');
      }
    }

    print('✅ Updated $updatedCount documents in $collectionName');
  }
}
